# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Thomas Tu''s Website
description:      'Website.'
url:              https://ephesosx.github.io
baseurl:          ""

# Options: 7, 8, 9, a, b, c, d, e, f
theme_id: "7"

author:
  name:           'Thomas Tu'
  url:            https://ephesosx.github.io/

# Blog configuration
has_blog:         True
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"

# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
